name: Build Kivy APK with Buildozer

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses-dev \
            libtinfo6 \
            cmake \
            libffi-dev \
            libssl-dev

      - name: Install Python dependencies
        run: |
          pip install buildozer==1.5.0
          pip install cython==0.29.34

      # ✅ Install Android SDK Command Line Tools
      - name: Install Android SDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-9477386_latest.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV

      # ✅ Accept licenses
      - name: Accept Android SDK licenses
        run: |
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses || true

      # ✅ Install required SDK packages (stable versions)
      - name: Install required SDK packages
        run: |
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager \
            "build-tools;33.0.2" \
            "platforms;android-33" \
            "platform-tools" \
            "ndk;25.1.8937393"

      - name: Build with Buildozer
        run: buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
