name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-dev python3-setuptools
        sudo apt-get install -y openjdk-17-jdk
        sudo apt-get install -y build-essential libssl-dev libffi-dev
        sudo apt-get install -y zlib1g-dev libncurses5-dev libncursesw5-dev
        sudo apt-get install -y libreadline-dev libsqlite3-dev liblzma-dev
        # Install 32-bit libraries for aidl compatibility
        sudo apt-get install -y libc6:i386 libstdc++6:i386 libncurses5:i386 lib32z1
        pip install --upgrade pip
        pip install buildozer cython==0.29.36

    - name: Install Android SDK
      run: |
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O commandlinetools.zip
        unzip commandlinetools.zip -d cmdline-tools
        mkdir -p android-sdk/cmdline-tools
        mv cmdline-tools/cmdline-tools android-sdk/cmdline-tools/tools
        ln -s tools android-sdk/cmdline-tools/latest
        export ANDROID_HOME=$PWD/android-sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
        yes | sdkmanager --sdk_root=$ANDROID_HOME --channel=0 "platforms;android-35"
        yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses
        yes | sdkmanager --sdk_root=$ANDROID_HOME --channel=0 "build-tools;35.0.0"
        yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses
        yes | sdkmanager --sdk_root=$ANDROID_HOME --channel=0 "platform-tools"
        yes | sdkmanager --sdk_root=$ANDROID_HOME --channel=0 "ndk;26.1.10909125"
        yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses
        echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
        echo "PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools" >> $GITHUB_ENV

    - name: Verify Build-Tools and Aidl
      run: |
        ls -la $ANDROID_HOME/build-tools
        find $ANDROID_HOME/build-tools -name "aidl" -exec ls -l {} \;
        # Test aidl execution
        $ANDROID_HOME/build-tools/35.0.0/aidl --version || echo "Aidl test failed"

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk
