name: Build Kivy APK with Buildozer

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-8-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev build-essential libstdc++6 aidl gettext automake libsdl2-dev libsdl2-ttf-dev libpango1.0-dev python3-pip
          sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java 1
          sudo update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac 1
          export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
          echo "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> $GITHUB_ENV

      - name: Install Python dependencies
        run: |
          python3 -m pip install --break-system-packages buildozer cython==0.29.34 setuptools

      - name: Clear Buildozer cache
        run: |
          rm -rf /home/runner/.buildozer
          rm -rf /home/runner/.android

      - name: Install Legacy Android SDK tools
        run: |
          wget -q https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -O sdk-tools.zip
          mkdir -p /home/runner/.buildozer/android/platform/android-sdk
          unzip -q sdk-tools.zip -d /home/runner/.buildozer/android/platform/android-sdk
          chmod +x /home/runner/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager
          echo "export ANDROIDSDK=/home/runner/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
          echo "export ANDROID_HOME=/home/runner/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$PATH:/home/runner/.buildozer/android/platform/android-sdk/tools/bin" >> $GITHUB_ENV

      - name: Pre-accept SDK licenses
        run: |
          licenses_dir="/home/runner/.buildozer/android/platform/android-sdk/licenses"
          mkdir -p "$licenses_dir"
          sdk_license="$licenses_dir/android-sdk-license"
          echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$sdk_license"
          echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> "$sdk_license"
          echo "24333f8a63b6825ea9c5514f83c2829b004
