name: Build Kivy APK

on:
  workflow_dispatch: # run manually
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-17-jdk unzip git wget

      - name: Install buildozer & Cython
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Initialize buildozer
        run: buildozer init

      - name: Copy custom spec
        run: cp buildozer.spec ./buildozer.spec

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: dataplotter-apk
          path: bin/*.apk
