name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-dev python3-setuptools
        sudo apt-get install -y openjdk-17-jdk
        sudo apt-get install -y build-essential libssl-dev libffi-dev
        sudo apt-get install -y zlib1g-dev libncurses5-dev libncursesw5-dev
        sudo apt-get install -y libreadline-dev libsqlite3-dev liblzma-dev
        pip install --upgrade pip
        pip install buildozer cython==0.29.36

    - name: Clear Buildozer Cache
      run: |
        rm -rf .buildozer

    - name: Install Android SDK
      run: |
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O commandlinetools.zip
        unzip commandlinetools.zip -d cmdline-tools
        mkdir -p android-sdk/cmdline-tools
        mv cmdline-tools/cmdline-tools android-sdk/cmdline-tools/tools
        ln -s tools android-sdk/cmdline-tools/latest
        export ANDROID_HOME=$PWD/android-sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
        nohup yes | sdkmanager --sdk_root=$ANDROID_HOME --channel=0 --verbose "platforms;android-35" > sdk_platforms.log 2>&1
        nohup yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses > sdk_licenses1.log 2>&1
        nohup yes | sdkmanager --sdk_root=$ANDROID_HOME --channel=0 --verbose "build-tools;35.0.0" > sdk_buildtools.log 2>&1
        nohup yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses > sdk_licenses2.log 2>&1
        nohup yes | sdkmanager --sdk_root=$ANDROID_HOME --channel=0 --verbose "platform-tools" > sdk_platformtools.log 2>&1
        nohup yes | sdkmanager --sdk_root=$ANDROID_HOME --channel=0 --verbose "ndk;26.1.10909125" > sdk_ndk.log 2>&1
        nohup yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses > sdk_licenses3.log 2>&1
        echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
        echo "PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools" >> $GITHUB_ENV
        # Dump logs for debugging
        cat sdk_*.log

    - name: Verify Build-Tools and Aidl
      run: |
        ls -la $ANDROID_HOME/build-tools
        find $ANDROID_HOME/build-tools -name "aidl" -exec ls -l {} \;

    - name: Build APK
      run: |
        buildozer -v android debug 2>&1 | tee buildozer.log
        # Dump the log if failed
        if [ ${PIPESTATUS[0]} -ne 0 ]; then cat buildozer.log; fi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk
      if-no-files-found: ignore

    - name: Upload Logs on Failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          buildozer.log
          sdk_*.log
