name: Build Kivy APK with Buildozer (Manual Setup)

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install system dependencies (including 32-bit libs)
        run: |
          sudo apt-get update
          # CRITICAL: Added lib32stdc++6 and lib32z1 for Android SDK tools
          sudo apt-get install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev build-essential lib32stdc++6 lib32z1

      - name: Install Python dependencies
        run: |
          pip install --upgrade setuptools cython==0.29.34 buildozer

      - name: Configure Buildozer and set requirements
        run: |
          # This is the most critical fix. It sets the requirements for your app.
          # It finds the requirements line and replaces it entirely.
          sed -i "s/^requirements =.*/requirements = python3,kivy==2.1.0,kivy-garden.graph,fpdf,arabic_reshaper,python-bidi,kivy_text_provider_pango,kivy_biometric @ git+https:\/\/github.com\/kivy-garden\/kivy_biometric.git/" buildozer.spec

          # Set other necessary configurations
          sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/' buildozer.spec
          sed -i 's/log_level = 1/log_level = 2/' buildozer.spec

      - name: Build with Buildozer
        run: |
          # No need for 'yes |' because we set the license in the .spec file
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-apk
          path: bin/*.apk
