name: Build Kivy APK with Buildozer

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev build-essential libstdc++6 aidl gettext automake libsdl2-dev libsdl2-ttf-dev

      - name: Install Python dependencies
        run: |
          pip install --upgrade setuptools cython==0.29.34 buildozer

      - name: Configure Buildozer spec
        run: |
          buildozer init || true
          sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/' buildozer.spec
          sed -i 's/log_level = 1/log_level = 2/' buildozer.spec || sed -i 's/log_level = 0/log_level = 2/' buildozer.spec
          sed -i 's/^requirements = .*/requirements = python3,kivy==2.3.0,kivy-garden.graph,fpdf,arabic-reshaper,python-bidi,kivy-biometric/' buildozer.spec
          sed -i 's/source.include_exts = .*/source.include_exts = py,png,jpg,kv,atlas,ttf,json,txt/' buildozer.spec
          sed -i 's/#android.permissions = .*/android.permissions = INTERNET,BIOMETRIC_AUTHENTICATE,USE_BIOMETRIC,USE_FINGERPRINT/' buildozer.spec
          sed -i 's/#android.sdk = .*/android.sdk = 33/' buildozer.spec
          sed -i 's/#android.ndk = .*/android.ndk = r25b/' buildozer.spec
          sed -i 's/#android.minapi = .*/android.minapi = 21/' buildozer.spec
          sed -i 's/#android.api = .*/android.api = 31/' buildozer.spec
          sed -i 's/#android.build_tools = .*/android.build_tools = 34.0.0/' buildozer.spec
          sed -i 's/p4a.branch = develop/p4a.branch = master/' buildozer.spec

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          workdir: .
          buildozer_version: stable

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
