name: Build Android APK (Final Version)

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-android:
    name: Build APK using official Kivy Docker image
    runs-on: ubuntu-latest

    # This container has all dependencies (Java, Python, 32-bit libs, etc.) pre-installed.
    container: kivy/buildozer:latest

    steps:
      - name: Checkout repository
        # This step checks out your code, including your new buildozer.spec file.
        uses: actions/checkout@v4

      - name: Set ownership of the checkout directory
        run: |
          sudo chown -R kivy:kivy .
      
      - name: Build the APK with Buildozer
        # Buildozer will now read all the correct settings from your committed buildozer.spec file.
        # No more sed commands are needed.
        run: |
          buildozer -v android debug

      - name: Upload the APK as a workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-apk
          path: bin/*.apk
