name: Build Kivy APK with Buildozer

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev build-essential libstdc++6 aidl gettext automake libsdl2-dev libsdl2-ttf-dev python3-pip

      - name: Install pipx
        run: |
          sudo apt-get install -y pipx
          pipx ensurepath

      - name: Install Python dependencies with pipx
        run: |
          pipx install buildozer
          pipx inject buildozer cython==0.29.34
          pipx inject buildozer setuptools

      - name: Install Android SDK command-line tools
        run: |
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d /tmp
          mkdir -p /home/runner/.buildozer/android/platform/android-sdk
          mv /tmp/cmdline-tools /home/runner/.buildozer/android/platform/android-sdk/cmdline-tools
          echo "export ANDROIDSDK=/home/runner/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$PATH:/home/runner/.buildozer/android/platform/android-sdk/cmdline-tools/bin" >> $GITHUB_ENV

      - name: Pre-accept SDK licenses
        run: |
          mkdir -p /home/runner/.buildozer/android/platform/android-sdk/licenses
          echo -e "8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > /home/runner/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
          echo -e "84831b9409646a918e30573bab4c9c91346d8abd" > /home/runner/.buildozer/android/platform/android-sdk/licenses/android-sdk-preview-license
          echo -e "33b6a2b64607f11b759f320ef9cc1fa173b4dcec" > /home/runner/.buildozer/android/platform/android-sdk/licenses/android-googletv-license
          echo -e "79120722343a6f3e6290098981203dad5e60b279" > /home/runner/.buildozer/android/platform/android-sdk/licenses/android-sdk-arm-dbt-license

      - name: Install Android build tools
        run: |
          /home/runner/.buildozer/android/platform/android-sdk/cmdline-tools/bin/sdkmanager --install "build-tools;34.0.0" "platforms;android-31" "ndk;25.2.9519653"

      - name: Configure Buildozer spec
        run: |
          buildozer init || true
          sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/' buildozer.spec
          sed -i 's/log_level = 1/log_level = 2/' buildozer.spec || sed -i 's/log_level = 0/log_level = 2/' buildozer.spec
          sed -i 's/^requirements = .*/requirements = python3,kivy==2.3.0,kivy-garden.graph,fpdf,arabic-reshaper,python-bidi,kivy-biometric/' buildozer.spec
          sed -i 's/source.include_exts = .*/source.include_exts = py,png,jpg,kv,atlas,ttf,json,txt/' buildozer.spec
          sed -i 's/#android.permissions = .*/android.permissions = INTERNET,BIOMETRIC_AUTHENTICATE,USE_BIOMETRIC,USE_FINGERPRINT/' buildozer.spec
          sed -i 's/#android.sdk = .*/android.sdk = 33/' buildozer.spec
          sed -i 's/#android.ndk = .*/android.ndk = r25b/' buildozer.spec
          sed -i 's/#android.minapi = .*/android.minapi = 21/' buildozer.spec
          sed -i 's/#android.api = .*/android.api = 31/' buildozer.spec
          sed -i 's/#android.build_tools = .*/android.build_tools = 34.0.0/' buildozer.spec
          sed -i 's/p4a.branch = develop/p4a.branch = master/' buildozer.spec

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:/home/runner/.local/bin
          yes | buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
