name: Build Kivy APK with Buildozer

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: /home/runner/android-sdk
      ANDROID_HOME: /home/runner/android-sdk
      ANDROIDSDK: /home/runner/android-sdk
      ANDROID_NDK_HOME: /home/runner/android-sdk/ndk/25.1.8937393
      ANDROIDNDK: /home/runner/android-sdk/ndk/25.1.8937393

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-17-jdk python3-pip \
            autoconf libtool pkg-config zlib1g-dev libncurses-dev \
            libtinfo6 cmake libffi-dev libssl-dev

      - name: Install Android SDK + NDK + Build-Tools
        run: |
          mkdir -p "$ANDROID_SDK_ROOT"
          cd "$ANDROID_SDK_ROOT"
          curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o cmdline-tools.zip
          unzip -q cmdline-tools.zip
          mkdir -p cmdline-tools/latest
          mv cmdline-tools/* cmdline-tools/latest/ || true
          rm -f cmdline-tools.zip

          # Install packages (include the one that triggers your error)
          yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_SDK_ROOT" \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;36.1.0-rc1" \
            "build-tools;33.0.2" \
            "ndk;25.1.8937393" \
            "cmdline-tools;latest"

          # Accept licenses for THIS SDK path
          yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_SDK_ROOT" --licenses

      - name: Install Python dependencies
        run: |
          python3 -m pip install -U pip
          pip install buildozer==1.5.0 cython==0.29.36

      - name: Build with Buildozer (force our SDK/NDK)
        run: |
          rm -rf ~/.buildozer   # ensure it cannot use its own SDK
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
