name: Build Kivy APK with Buildozer (Solution 2)

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev build-essential libstdc++6 aidl gettext automake

      - name: Install Python dependencies
        run: |
          pip install --upgrade setuptools cython==0.29.34 buildozer

      - name: Initialize and configure Buildozer
        run: |
          buildozer init || true
          sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/' buildozer.spec
          sed -i 's/log_level = 1/log_level = 2/' buildozer.spec || sed -i 's/log_level = 0/log_level = 2/' buildozer.spec
          sed -i 's/#android.sdk = 20/android.sdk = 33/' buildozer.spec
          sed -i 's/#android.ndk = 25b/android.ndk = 25b/' buildozer.spec
          sed -i 's/#android.minapi = 21/android.minapi = 21/' buildozer.spec
          sed -i 's/#android.api = 31/android.api = 31/' buildozer.spec
          sed -i 's/#android.build_tools = 34.0.0/android.build_tools = 34.0.0/' buildozer.spec

      - name: Build with Buildozer
        run: yes | buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
