name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04  # Use 22.04 for better compatibility with Buildozer/Python 3.10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Stable version for Buildozer; avoids 3.12 distutils issues

      - name: Get Date
        id: get-date
        run: echo "date=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache Buildozer global directory
        uses: actions/cache@v4
        with:
          path: ~/.buildozer_global
          key: buildozer-global-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            buildozer-global-${{ runner.os }}-

      - name: Cache Buildozer directory
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-buildozer-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-${{ steps.get-date.outputs.date }}-
            ${{ runner.os }}-buildozer-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -f  # Fix any broken dependencies early
          # Hold potential conflicting packages to prevent breakage
          sudo apt-mark hold libunwind8
          sudo apt-get install -y --fix-missing --allow-downgrades --no-install-recommends \
            git zip unzip openjdk-17-jdk-headless \
            build-essential python3-dev libffi-dev libssl-dev zlib1g-dev \
            libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev \
            libncursesw5-dev xz-utils tk-dev libffi-dev libxml2-dev libxmlsec1-dev \
            liblzma-dev libgdbm-dev libnss3-dev libjpeg-dev libpng-dev \
            libavcodec-dev libavformat-dev libswscale-dev libgstreamer1.0-dev libunwind-dev \
            libgstreamer-plugins-base1.0-dev \
            libsdl2-dev libsdl2-image-dev \
            libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev \
            libavformat-dev libavcodec-dev gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-base gstreamer1.0-plugins-bad

      - name: Install Buildozer dependencies
        run: pip install --user --upgrade cython==0.29.36 buildozer

      - name: Build APK
        run: |
          export PATH=$HOME/.local/bin:$PATH
          buildozer -v android debug
        env:
          ANDROIDSDK: ${{ runner.temp }}/android-sdk  # Optional: Use temp dir if caching issues persist

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk-${{ steps.get-date.outputs.date }}
          path: bin/*.apk
